### ISSUE TITLE
test issue for mentions notification testing

### ISSUE THREAD

**Issue by yoyokenny** [yoyokenny/MultiMCPortable#2]
@peterix Let me know if that notified you.

**Comment by peterix** [comment]
Yes.

**Comment by peterix** [comment]
Odd... I could swear MultiMC was already a fully portable application. It would take considerable effort to make it non-portable :smile:

**Comment by yoyokenny** [comment]
It's just a PAF package for PortableApps.com that can't be used yet, the PortableApps.com Launcher can't edit paths in the config file due to unix-style line endings.
Also, that whole java timestamp thing is really annoying, not compatible with portable platforms that distribute portable java installs.

**Comment by peterix** [comment]
Alright... here are some random thoughts.

RE: timestamps
All it does is re-check that the java is still the same. If not, it will run more checks. If they fail, user intervention is necessary.

RE: Portable java...
Some sort of 'needs java' flag simply won't do. Look at this: https://portableapps.com/apps/utilities/java_portable - the moment it updates to Java 9, it will break modded Minecraft completely.

You might have to bundle a specific version of Java inside the MultiMC folder and use a relative path to the `javaw.exe` (So something like `jre/bin/javaw.exe`). 8u51 is the best for maximum compatibility. Newer versions break certain Intel integrated GPU drivers on Windows 10. Java 9 is and will remain useless for all current versions of Minecraft.

Instead of editing a file, you could supply a `multimc.cfg` with just the lines you need - which shouldn't be many.

If you need to change the data folder MultiMC uses, use the `-d` argument.

See:
```
 ~/MultiMC  $  ./MultiMC --help
MultiMC Dir: /home/mrazekp/MultiMC
Usage: /home/mrazekp/MultiMC/bin/MultiMC [-h] [-V] [-d <dir>] [-l <launch>] [--alive]

Options & Switches:
  -h, --help            display this help and exit.
  -V, --version         display program version and exit.
  -d, --dir <dir>       use the supplied folder as MultiMC root instead of the binary location (use '.' for current)
  -l, --launch <launch> launch the specified instance (by instance ID)
  --alive               write a small 'live.check' file after MultiMC starts
```

**Comment by yoyokenny** [comment]
Probably gonna scrap it anyway.
